name ="John"
age = 30
price = 19.99
is_student = True
print("my name is " + name + " and i am " + str(age) + " years old and the price is $" + str(price))
print(name)

print( type(name))
print (type(age))

print (type(price))
print (type(is_student))
name1 = "Bob"
name2 = 'Bob'
name3 = '''Bob'''
print(name1)
print(name2)
print(name3)
age1 = 30
old= False
a=None
print(type (old))
print(type(a))
# print("my name is " + name + " and i am " + str(age) + " years old and the price is $" + str(price))
# print(name)
a = 10
b = 20
# sum = a + b
print(a == b)
print(a -b)
print(a * b)
print(a / b)
print(a % b)
